version: "3.4"

x-app: &default-app
  env_file:
    - ".env"
  stop_grace_period: "3s"
  tty: true
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
  healthcheck:
    interval: 1m30s
    timeout: 10s
    retries: 3
    start_period: 40s

services:
  frontend:
    <<: *default-app
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
#      args:
#        - NODE_ENV=${NODE_ENV}
#    image: fincal-frontend
    entrypoint: npm run dev
    working_dir: /app/frontend
    ports:
      - ${FRONTEND_CLIENT_PORT_FORWARD}:${FRONTEND_CLIENT_PORT}
    expose:
      - ${FRONTEND_CLIENT_PORT}
    healthcheck:
      test: "${FRONTEND_HEALTHCHECK_TEST}"
    volumes:
      - frontend:/app/frontend:delegated
#      - /app/frontend/node_modules
    networks:
      - backend
      - frontend
    tty: true

  backend:
    <<: *default-app
    build:
      context: "./services/backend"
      dockerfile: Dockerfile
#    image: fincal-backend
    working_dir: /app/backend
    ports:
      - ${BACKEND_CLIENT_PORT_FORWARD}:${BACKEND_CLIENT_PORT}
    expose:
      - ${BACKEND_CLIENT_PORT}
    healthcheck:
      test: "${FRONTEND_HEALTHCHECK_TEST}"
    volumes:
      - backend:/app/backend:delegated
    networks:
      - backend
      - frontend

  db:
    <<: *default-app
    image: mysql:8.0.22
    container_name: fincal-mysql
    ports:
      - ${DB_CLIENT_PORT_FORWARD}:${DB_CLIENT_PORT}
    expose:
      - ${DB_CLIENT_PORT}
    command: --init-file /data/sql/fincal_init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./services/backend/database/sql:/data/sql
    networks:
      - backend

volumes:
  frontend:
  backend:
  db-data:

networks:
  frontend:
  backend:
