version: "3.4"

x-app: &default-app
  env_file:
    - ".env"
  stop_grace_period: "3s"
  tty: true
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
  healthcheck:
    interval: 1m30s
    timeout: 10s
    retries: 3
    start_period: 40s

services:
  frontend:
    <<: *default-app
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    entrypoint: npm run dev
    working_dir: /app/frontend
    ports:
      - ${FRONTEND_CLIENT_PORT_FORWARD}:${FRONTEND_CLIENT_PORT}
    expose:
      - ${FRONTEND_CLIENT_PORT}
    healthcheck:
      test: "${FRONTEND_HEALTHCHECK_TEST}"
    volumes:
      - frontend:/app/frontend:delegated
    networks:
      - mynetwork

  backend:
    <<: *default-app
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    working_dir: /app/backend
    ports:
      - ${BACKEND_CLIENT_PORT_FORWARD}:${BACKEND_CLIENT_PORT}
    expose:
      - ${BACKEND_CLIENT_PORT}
    healthcheck:
      test: ${FRONTEND_HEALTHCHECK_TEST}
    volumes:
      - backend:/app/backend:delegated
    networks:
      - mynetwork

  mysql:
    <<: *default-app
    build:
      context: ./services/database
      dockerfile: Dockerfile
    ports:
      - ${DB_CLIENT_PORT_FORWARD}:${DB_CLIENT_PORT}
    expose:
      - ${DB_CLIENT_PORT}
    command: --init-file /database/sql/fincal_init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
      - ./services/database/sql:/database/sql
    networks:
      - mynetwork

volumes:
  frontend:
  backend:
  db-data:

networks:
  mynetwork: